name: Football Scraper

on:
  schedule:
    - cron: "0 */8 * * *"   # Runs every 8 hours
  workflow_dispatch:        # Allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Run scraper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        run: python scraper.py
